/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Domain.ClienteSingleton;
import Utility.GestionXML;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author catas
 */
public class JIFAgregarAmigos extends javax.swing.JInternalFrame implements Runnable {

    /**
     * Creates new form JIFAgregarAmigos
     */
    public JIFAgregarAmigos() {
        initComponents();
        Thread t=new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jbtnEnviarSolicitud = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar amigos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese el nombre de usuario a agregar:");

        jtfNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbtnEnviarSolicitud.setText("Enviar solicitud");
        jbtnEnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnviarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbtnEnviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnEnviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnviarSolicitudActionPerformed
        //envia la solicitud de amistad al cliente deseado.
        ClienteSingleton clienteSingleton=ClienteSingleton.getInstance();
        GestionXML gestionXML= new GestionXML();
        
        String mensaje= gestionXML.xmlToString(gestionXML.agregarAccionSimple("agregarAmigo", this.jtfNombre.getText()));
        
        clienteSingleton.enviarDatos(mensaje);
        
    }//GEN-LAST:event_jbtnEnviarSolicitudActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnEnviarSolicitud;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        ClienteSingleton cs=ClienteSingleton.getInstance();
        while (true) {            
            try {
                if (cs.isVerificado()) {
                    if (cs.getRegistrado().equals("si")) {
                        JOptionPane.showMessageDialog(this, "Solicitud de amistad enviada");
                    }else{
                        JOptionPane.showMessageDialog(this, "Jugador no encontrado");
                    }
                    cs.setVerificado(false);
                    cs.setRegistrado("");
                }
                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(JIFAgregarAmigos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
